In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("order_history_kaggle_data.csv")
print(df.head())

   Restaurant ID Restaurant name   Subzone       City    Order ID  \
0       20320607           Swaad  Sector 4  Delhi NCR  6168884918
1       20320607           Swaad  Sector 4  Delhi NCR  6170707559
2       20320607           Swaad  Sector 4  Delhi NCR  6169375019
3       20320607           Swaad  Sector 4  Delhi NCR  6151677434
4       20320607           Swaad  Sector 4  Delhi NCR  6167540897

               Order Placed At Order Status         Delivery Distance  \
0  11:38 PM, September 10 2024    Delivered  Zomato Delivery      3km
1  11:34 PM, September 10 2024    Delivered  Zomato Delivery      2km
2  03:52 PM, September 10 2024    Delivered  Zomato Delivery     <1km
3  03:45 PM, September 10 2024    Delivered  Zomato Delivery      2km
4  03:04 PM, September 10 2024    Delivered  Zomato Delivery      2km

                                      Items in order  ... Rating Review  \
0  1 x Grilled Chicken Jamaican Tender, 1 x Grill...  ...    NaN    NaN
1  1 x Peri Peri Fries, 1 x Fried Chicken Angara ...  ...    NaN    NaN
2              1 x Bone in Peri Peri Grilled Chicken  ...    NaN    NaN
3  1 x Fried Chicken Ghostbuster Tender, 1 x Anga...  ...    4.0    NaN
4  1 x Peri Peri Krispers, 1 x Fried Chicken Anga...  ...    NaN    NaN

   Cancellation / Rejection reason  Restaurant compensation (Cancellation)  \
0                              NaN                                     NaN
1                              NaN                                     NaN
2                              NaN                                     NaN
3                              NaN                                     NaN
4                              NaN                                     NaN

   Restaurant penalty (Rejection)  KPT duration (minutes)  \
0                             NaN                   18.35
1                             NaN                   16.95
2                             NaN                   14.05
3                             NaN                   19.00
4                             NaN                   15.97

   Rider wait time (minutes)  Order Ready Marked  Customer complaint tag  \
0                       11.6           Correctly                     NaN
1                        3.6           Correctly                     NaN
2                       12.2           Correctly                     NaN
3                        3.3           Correctly                     NaN
4                        1.0           Correctly                     NaN

                                         Customer ID
0  5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1  0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2  f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3  1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4  d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

[5 rows x 29 columns]

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21321 entries, 0 to 21320
Data columns (total 29 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Restaurant ID                                       21321 non-null  int64
 1   Restaurant name                                     21321 non-null  object
 2   Subzone                                             21321 non-null  object
 3   City                                                21321 non-null  object
 4   Order ID                                            21321 non-null  int64
 5   Order Placed At                                     21321 non-null  object
 6   Order Status                                        21321 non-null  object
 7   Delivery                                            21321 non-null  object
 8   Distance                                            21321 non-null  object
 9   Items in order                                      21321 non-null  object
 10  Instructions                                        720 non-null    object
 11  Discount construct                                  15823 non-null  object
 12  Bill subtotal                                       21321 non-null  float64
 13  Packaging charges                                   21321 non-null  float64
 14  Restaurant discount (Promo)                         21321 non-null  float64
 15  Restaurant discount (Flat offs, Freebies & others)  21321 non-null  float64
 16  Gold discount                                       21321 non-null  float64
 17  Brand pack discount                                 21321 non-null  float64
 18  Total                                               21321 non-null  float64
 19  Rating                                              2491 non-null   float64
 20  Review                                              296 non-null    object
 21  Cancellation / Rejection reason                     186 non-null    object
 22  Restaurant compensation (Cancellation)              133 non-null    float64
 23  Restaurant penalty (Rejection)                      3 non-null      float64
 24  KPT duration (minutes)                              21026 non-null  float64
 25  Rider wait time (minutes)                           21153 non-null  float64
 26  Order Ready Marked                                  21321 non-null  object
 27  Customer complaint tag                              469 non-null    object
 28  Customer ID                                         21321 non-null  object
dtypes: float64(12), int64(2), object(15)
memory usage: 4.7+ MB

,Restaurant ID,Order ID,Bill subtotal,Packaging charges,Restaurant discount (Promo),"Restaurant discount (Flat offs, Freebies & others)",Gold discount,Brand pack discount,Total,Rating,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes)
count,2.132100e+04,2.132100e+04,21321.000000,21321.000000,21321.000000,21321.000000,21321.000000,21321.000000,21321.000000,2491.000000,133.000000,3.0,21026.000000,21153.000000
mean,2.074413e+07,6.354622e+09,750.076838,32.564592,65.091816,31.795058,0.099128,3.039324,682.616113,4.356885,356.409549,0.0,17.332960,4.825070
std,2.447193e+05,1.230263e+08,498.759428,22.235898,85.401604,131.487091,3.264261,17.070780,465.313977,1.181472,328.128240,0.0,6.283388,4.982591
min,2.032061e+07,6.086767e+09,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.500000,1.000000,83.580000,0.0,0.000000,0.100000
25%,2.063570e+07,6.250751e+09,459.000000,18.450000,0.000000,0.000000,0.000000,0.000000,387.450000,4.000000,191.950000,0.0,13.380000,1.000000
50%,2.065987e+07,6.357715e+09,629.000000,28.450000,80.000000,0.000000,0.000000,0.000000,597.450000,5.000000,272.580000,0.0,16.330000,3.100000
75%,2.088265e+07,6.456827e+09,899.000000,39.950000,100.000000,0.000000,0.000000,0.000000,837.900000,5.000000,397.840000,0.0,20.050000,7.400000
max,2.152306e+07,6.573392e+09,16080.000000,603.000000,4020.000000,7787.000000,280.100000,554.800000,12663.000000,5.000000,3236.980000,0.0,90.870000,73.800000

In [ ]:
df.isnull().sum()

Restaurant ID                                             0
Restaurant name                                           0
Subzone                                                   0
City                                                      0
Order ID                                                  0
Order Placed At                                           0
Order Status                                              0
Delivery                                                  0
Distance                                                  0
Items in order                                            0
Instructions                                          20601
Discount construct                                     5498
Bill subtotal                                             0
Packaging charges                                         0
Restaurant discount (Promo)                               0
Restaurant discount (Flat offs, Freebies & others)        0
Gold discount                                             0
Brand pack discount                                       0
Total                                                     0
Rating                                                18830
Review                                                21025
Cancellation / Rejection reason                       21135
Restaurant compensation (Cancellation)                21188
Restaurant penalty (Rejection)                        21318
KPT duration (minutes)                                  295
Rider wait time (minutes)                               168
Order Ready Marked                                        0
Customer complaint tag                                20852
Customer ID                                               0
dtype: int64

In [ ]:
df.fillna(method='ffill', inplace=True)

/tmp/ipykernel_542/3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df["Order Placed At"] = pd.to_datetime(df["Order Placed At"])

/tmp/ipykernel_542/2126483622.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Order Placed At"] = pd.to_datetime(df["Order Placed At"])

In [ ]:
df["Order Placed At"].head()

0   2024-09-10 23:38:00
1   2024-09-10 23:34:00
2   2024-09-10 15:52:00
3   2024-09-10 15:45:00
4   2024-09-10 15:04:00
Name: Order Placed At, dtype: datetime64[ns]

In [ ]:
print(df["Order Placed At"].dtype)

datetime64[ns]

In [ ]:
df["Items in order"] = pd.to_numeric(df["Items in order"], errors="coerce")
df["Revenue_per_item"] = df["Total"] / df["Items in order"]
print(df[["Total","Items in order","Revenue_per_item"]].head())

     Total  Items in order  Revenue_per_item
0   666.75             NaN               NaN
1  1054.20             NaN               NaN
2   241.50             NaN               NaN
3   567.00             NaN               NaN
4   529.20             NaN               NaN

In [ ]:
df.sort_values(by="Total", ascending=False).head()

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID,Revenue_per_item
8092,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6293780158,2024-10-23 11:25:00,Delivered,Zomato Delivery,10km,NaN,...,Loved it! please maintain this quality and qua...,Cancelled by Zomato,397.84,0.0,90.87,68.0,Correctly,Poor taste or quality,313956167f82ffd9bcca4d100cdacf6258d58e0f62055a...,NaN
19221,20659868,Aura Pizzas,Sector 4,Delhi NCR,6521078270,2025-01-16 17:04:00,Delivered,Zomato Delivery,1km,NaN,...,I felt the dips have become quite watered down...,Cancelled by Customer,171.78,0.0,49.40,8.5,Incorrectly,Non-refunded complaint,4262526edf129f7758906244a68db2b0b6c77fe002cfaa...,NaN
15329,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6433831042,2024-12-14 11:30:00,Delivered,Zomato Delivery,4km,NaN,...,delicious sourdough pizza and garlic brea. the...,Cancelled by Zomato,641.77,0.0,88.57,53.2,Correctly,Non-refunded complaint,e7effd922b1555e4013df178577e43ddb5fe649c39c8b3...,NaN
8059,20882652,Aura Pizzas,DLF Phase 1,Delhi NCR,6290509586,2024-10-26 12:52:00,Delivered,Zomato Delivery,4km,NaN,...,Loved it! please maintain this quality and qua...,Cancelled by Customer,397.84,0.0,40.15,11.3,Incorrectly,Poor packaging or spillage,d429bb04060384f2f6480bd264ead2929e9b939d9f0362...,NaN
15144,20659868,Aura Pizzas,Sector 4,Delhi NCR,6432747136,2024-12-13 13:06:00,Delivered,Zomato Delivery,<1km,NaN,...,Herbed potato was missing from the order. Rest...,Cancelled by Customer,356.16,0.0,5.12,51.5,Incorrectly,Poor taste or quality,447f3d277e77e80188986fcbd853a877d6d8e49cd4a9ec...,NaN

In [ ]:
df["City"].value_counts()

City
Delhi NCR    21321
Name: count, dtype: int64

In [ ]:
df[df["City"].str.strip() == "Delhi NCR"]

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID,Revenue_per_item
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,2024-09-10 23:38:00,Delivered,Zomato Delivery,3km,NaN,...,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...,NaN
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,2024-09-10 23:34:00,Delivered,Zomato Delivery,2km,NaN,...,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...,NaN
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,2024-09-10 15:52:00,Delivered,Zomato Delivery,<1km,NaN,...,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...,NaN
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,2024-09-10 15:45:00,Delivered,Zomato Delivery,2km,NaN,...,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...,NaN
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,2024-09-10 15:04:00,Delivered,Zomato Delivery,2km,NaN,...,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21316,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6568490993,2025-01-30 03:26:00,Delivered,Zomato Delivery,5km,NaN,...,Perfect meal for one! Always super flavourful.,Cancelled by Zomato,637.14,0.0,14.32,9.0,Correctly,Wrong item(s) delivered,c6ee80eb35f2ef1630fd93ea88f8c0ac27eff57229a6d5...,NaN
21317,21467440,The Chicken Junction,Chittaranjan Park,Delhi NCR,6564842673,2025-01-29 02:44:00,Delivered,Zomato Delivery,5km,NaN,...,Perfect meal for one! Always super flavourful.,Cancelled by Zomato,637.14,0.0,14.32,10.8,Missed,Wrong item(s) delivered,d2a0153ba6512894c1bebe974f6898ba10df50abc2c954...,NaN
21318,21523055,Masala Junction,Sector 4,Delhi NCR,6553527557,2025-01-24 22:05:00,Delivered,Zomato Delivery,8km,NaN,...,Yummy food! Delicious food! Lip smacking food!...,Cancelled by Zomato,637.14,0.0,16.27,9.4,Incorrectly,Wrong item(s) delivered,0b6168cbaf96aa5a0ae6b46d19d83ec9cad0d9508d43d7...,NaN
21319,21523055,Masala Junction,Sector 4,Delhi NCR,6541170157,2025-01-21 14:27:00,Delivered,Zomato Delivery,9km,NaN,...,The peri peri fries were truly so tasty and de...,Cancelled by Zomato,637.14,0.0,12.77,1.3,Correctly,Wrong item(s) delivered,410b3e056e511e3423d9497c629ca897f91cace2a2a732...,NaN
21320,21523055,Masala Junction,Sector 4,Delhi NCR,6543973010,2025-01-21 02:55:00,Delivered,Zomato Delivery,3km,NaN,...,The peri peri fries were truly so tasty and de...,Cancelled by Zomato,637.14,0.0,16.52,8.7,Correctly,Wrong item(s) delivered,1f885b307de98a52c7b6f75a8813cc130e3049ad0be017...,NaN

In [ ]:
df.groupby("City")["Total"].sum()

City
Delhi NCR    14554058.14
Name: Total, dtype: float64

In [ ]:
df["Order Status"].value_counts()

Order Status
Delivered           21131
Rejected              158
Returned               25
Return cancelled        3
Picked up               3
Timed out               1
Name: count, dtype: int64

In [ ]:
df.groupby("Restaurant name")["Total"].sum().sort_values(ascending=False).head(10)

Restaurant name
Aura Pizzas             10751617.42
Swaad                    3545521.86
Tandoori Junction         133665.95
Dilli Burger Adda         101709.62
The Chicken Junction       12380.99
Masala Junction             9162.30
Name: Total, dtype: float64

In [ ]:
df["Order_Category"] = df["Total"].apply(lambda x: "High" if x>500 else "Medium" if x>200 else "Low")
df[["Total","Order_Category"]].head()

     Total Order_Category
0   666.75           High
1  1054.20           High
2   241.50         Medium
3   567.00           High
4   529.20           High

In [ ]:
df.rename(columns={"Restaurant name":"Restaurant"}, inplace=True)

In [ ]:
df["City"] = df["City"].str.upper()
print(df["City"].str.upper())

0        DELHI NCR
1        DELHI NCR
2        DELHI NCR
3        DELHI NCR
4        DELHI NCR
           ...
21316    DELHI NCR
21317    DELHI NCR
21318    DELHI NCR
21319    DELHI NCR
21320    DELHI NCR
Name: City, Length: 21321, dtype: object

In [ ]:
df["City"] = df["City"].str.lower()
print(df["City"].str.lower())

0        delhi ncr
1        delhi ncr
2        delhi ncr
3        delhi ncr
4        delhi ncr
           ...
21316    delhi ncr
21317    delhi ncr
21318    delhi ncr
21319    delhi ncr
21320    delhi ncr
Name: City, Length: 21321, dtype: object

In [ ]:
top_restaurants = df.groupby("Restaurant")["Total"].sum().sort_values(ascending=False).head(10)
print(top_restaurants)

Restaurant
Aura Pizzas             10751617.42
Swaad                    3545521.86
Tandoori Junction         133665.95
Dilli Burger Adda         101709.62
The Chicken Junction       12380.99
Masala Junction             9162.30
Name: Total, dtype: float64

In [ ]:
df["Distance"].mean()
df.groupby("City")["Distance"].mean()
df[["Distance","Total"]].corr()

          Distance     Total
Distance  1.000000  0.116465
Total     0.116465  1.000000

In [ ]:
df["Order Placed At"] = pd.to_datetime(df["Order Placed At"], errors="coerce")
df["Month"] = df["Order Placed At"].dt.month
df["Month_Name"] = df["Order Placed At"].dt.month_name()

In [ ]:
monthly_orders = df.groupby("Month_Name")["Order ID"].count().sort_values(ascending=False)

print(monthly_orders)

Month_Name
November     4491
December     4301
October      4277
September    4241
January      4011
Name: Order ID, dtype: int64

In [ ]:
df["Day"] = df["Order Placed At"].dt.day
df["Weekday"] = df["Order Placed At"].dt.day_name()
df["Hour"] = df["Order Placed At"].dt.hour

In [ ]:
df["Weekday"].value_counts()

Weekday
Saturday     3923
Friday       3403
Wednesday    3077
Sunday       2958
Tuesday      2885
Thursday     2879
Monday       2196
Name: count, dtype: int64

In [ ]:
df["Hour"].value_counts().sort_index()

Hour
0      957
1      833
2      488
3      389
4        5
11     305
12     909
13    1142
14    1032
15     824
16     905
17    1069
18    1611
19    2419
20    2912
21    2296
22    1748
23    1477
Name: count, dtype: int64

In [ ]:
distance_array = np.array(df["Distance"])
print("Average Distance:", np.mean(distance_array))
print("Max Distance:", np.max(distance_array))
print("Min Distance:", np.min(distance_array))

Average Distance: 4.182730641151916
Max Distance: 21
Min Distance: 1

In [ ]:
new_distance = distance_array + 2

In [ ]:
matrix = np.array([[2,3],[4,5]])
print("Determinant:",np.linalg.det(matrix))
print("Inverse:",np.linalg.inv(matrix))
print("Eigenvalues:",np.linalg.eig(matrix)[0])

Determinant: -2.0
Inverse: [[-2.5  1.5]
 [ 2.  -1. ]]
Eigenvalues: [-0.27491722  7.27491722]

In [ ]:
high_orders = df[df["Total"] > 500]

print(high_orders.head())

   Restaurant ID Restaurant   Subzone       City    Order ID  \
0       20320607      Swaad  Sector 4  delhi ncr  6168884918
1       20320607      Swaad  Sector 4  delhi ncr  6170707559
3       20320607      Swaad  Sector 4  delhi ncr  6151677434
4       20320607      Swaad  Sector 4  delhi ncr  6167540897
5       20320607      Swaad  Sector 4  delhi ncr  6164725184

      Order Placed At Order Status         Delivery  Distance  Items in order  \
0 2024-09-10 23:38:00    Delivered  Zomato Delivery         3             NaN
1 2024-09-10 23:34:00    Delivered  Zomato Delivery         2             NaN
3 2024-09-10 15:45:00    Delivered  Zomato Delivery         2             NaN
4 2024-09-10 15:04:00    Delivered  Zomato Delivery         2             NaN
5 2024-09-10 12:28:00    Delivered  Zomato Delivery         1             NaN

   ... Order Ready Marked Customer complaint tag  \
0  ...          Correctly                    NaN
1  ...          Correctly                    NaN
3  ...          Correctly                    NaN
4  ...          Correctly                    NaN
5  ...          Correctly                    NaN

                                         Customer ID  Revenue_per_item  \
0  5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...               NaN
1  0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...               NaN
3  1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...               NaN
4  d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...               NaN
5  4103fd4f3ee2166d322e76fabd420ae15f14a2816ca5a3...               NaN

   Order_Category  Month  Month_Name  Day  Weekday  Hour
0            High      9   September   10  Tuesday    23
1            High      9   September   10  Tuesday    23
3            High      9   September   10  Tuesday    15
4            High      9   September   10  Tuesday    15
5            High      9   September   10  Tuesday    12

[5 rows x 36 columns]

In [ ]:
top_rated = df[df["Rating"] > 4]

print(top_rated.head())

   Restaurant ID Restaurant   Subzone       City    Order ID  \
5       20320607      Swaad  Sector 4  delhi ncr  6164725184
6       20320607      Swaad  Sector 4  delhi ncr  6151460444
7       20320607      Swaad  Sector 4  delhi ncr  6167255032
8       20320607      Swaad  Sector 4  delhi ncr  6167184688
9       20320607      Swaad  Sector 4  delhi ncr  6163081676

      Order Placed At Order Status         Delivery  Distance  Items in order  \
5 2024-09-10 12:28:00    Delivered  Zomato Delivery         1             NaN
6 2024-09-10 00:03:00    Delivered  Zomato Delivery         6             NaN
7 2024-09-09 22:54:00    Delivered  Zomato Delivery         2             NaN
8 2024-09-09 22:51:00    Delivered  Zomato Delivery         1             NaN
9 2024-09-09 15:22:00    Delivered  Zomato Delivery         1             NaN

   ... Order Ready Marked Customer complaint tag  \
5  ...          Correctly                    NaN
6  ...        Incorrectly                    NaN
7  ...          Correctly                    NaN
8  ...          Correctly                    NaN
9  ...          Correctly                    NaN

                                         Customer ID  Revenue_per_item  \
5  4103fd4f3ee2166d322e76fabd420ae15f14a2816ca5a3...               NaN
6  24d7ca74eb1efe217e88062d2519403ba11d62f5953186...               NaN
7  fa1710c1c41dd4f29b810b78f8e7c08a356ca0fdc39307...               NaN
8  c521ccf21e7bb2207c3f08d578b6e028d2c3b25986cb35...               NaN
9  ac2ee09679412d4248884cdfd7637d9b3529eeac0e2f27...               NaN

   Order_Category  Month  Month_Name  Day  Weekday  Hour
5            High      9   September   10  Tuesday    12
6          Medium      9   September   10  Tuesday     0
7          Medium      9   September    9   Monday    22
8          Medium      9   September    9   Monday    22
9          Medium      9   September    9   Monday    15

[5 rows x 36 columns]