<a href="https://colab.research.google.com/github/preethiusha05/python_pratice/blob/main/Numpy_Pandas_Mini_Project_Food_Delivery_Orders_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("food_delivery_orders.csv")
df.head()

,Order_ID,Customer_ID,Restaurant,Food_Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method
0,1001,251,Pizza Palace,Dosa,5,417,53,Madurai,2025-04-15,Cash
1,1002,292,South Delight,Fried Rice,3,264,25,Coimbatore,2025-02-06,Card
2,1003,214,Spice Hub,Pizza,1,324,41,Chennai,2025-01-24,UPI
3,1004,271,South Delight,Fried Rice,5,406,30,Madurai,2025-04-03,UPI
4,1005,260,Urban Tadka,Sandwich,2,333,35,Madurai,2025-04-23,Card

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        50 non-null     int64
 1   Customer_ID     50 non-null     int64
 2   Restaurant      50 non-null     object
 3   Food_Item       50 non-null     object
 4   Quantity        50 non-null     int64
 5   Price           50 non-null     int64
 6   Delivery_Time   50 non-null     int64
 7   City            50 non-null     object
 8   Order_Date      50 non-null     object
 9   Payment_Method  50 non-null     object
dtypes: int64(5), object(5)
memory usage: 4.0+ KB

In [4]:
df.describe()

         Order_ID  Customer_ID   Quantity       Price  Delivery_Time
count    50.00000    50.000000  50.000000   50.000000      50.000000
mean   1025.50000   250.840000   3.120000  305.660000      39.360000
std      14.57738    28.132601   1.465801   98.370522      11.985978
min    1001.00000   201.000000   1.000000  101.000000      20.000000
25%    1013.25000   224.500000   2.000000  226.000000      28.500000
50%    1025.50000   255.500000   3.000000  299.500000      39.000000
75%    1037.75000   273.500000   4.000000  389.500000      50.750000
max    1050.00000   299.000000   5.000000  486.000000      59.000000

In [5]:
df.isnull().sum()

Order_ID          0
Customer_ID       0
Restaurant        0
Food_Item         0
Quantity          0
Price             0
Delivery_Time     0
City              0
Order_Date        0
Payment_Method    0
dtype: int64

In [32]:
df.dropna(inplace=True)
df.head()

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category
0,1001,251,pizza palace,Dosa,5,417,53,MADURAI,2025-04-15,Cash,2085,High
1,1002,292,south delight,Fried Rice,3,264,25,COIMBATORE,2025-02-06,Card,792,High
2,1003,214,spice hub,Pizza,1,324,41,CHENNAI,2025-01-24,UPI,324,Medium
3,1004,271,south delight,Fried Rice,5,406,30,MADURAI,2025-04-03,UPI,2030,High
4,1005,260,urban tadka,Sandwich,2,333,35,MADURAI,2025-04-23,Card,666,High

In [42]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df.head()

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category,Day,Weekday,Month
0,1001,251,pizza palace,Dosa,5,417,53,MADURAI,2025-04-15,Cash,2085,High,15,Tuesday,4
1,1002,292,south delight,Fried Rice,3,264,25,COIMBATORE,2025-02-06,Card,792,High,6,Thursday,2
2,1003,214,spice hub,Pizza,1,324,41,CHENNAI,2025-01-24,UPI,324,Medium,24,Friday,1
3,1004,271,south delight,Fried Rice,5,406,30,MADURAI,2025-04-03,UPI,2030,High,3,Thursday,4
4,1005,260,urban tadka,Sandwich,2,333,35,MADURAI,2025-04-23,Card,666,High,23,Wednesday,4

In [8]:
df["Total_Price"] = df["Quantity"] * df["Price"]

df.head()

,Order_ID,Customer_ID,Restaurant,Food_Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price
0,1001,251,Pizza Palace,Dosa,5,417,53,Madurai,2025-04-15,Cash,2085
1,1002,292,South Delight,Fried Rice,3,264,25,Coimbatore,2025-02-06,Card,792
2,1003,214,Spice Hub,Pizza,1,324,41,Chennai,2025-01-24,UPI,324
3,1004,271,South Delight,Fried Rice,5,406,30,Madurai,2025-04-03,UPI,2030
4,1005,260,Urban Tadka,Sandwich,2,333,35,Madurai,2025-04-23,Card,666

In [9]:
df.sort_values(by="Total_Price", ascending=False).head()

,Order_ID,Customer_ID,Restaurant,Food_Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price
19,1020,237,South Delight,Pasta,5,486,26,Chennai,2025-01-25,Cash,2430
0,1001,251,Pizza Palace,Dosa,5,417,53,Madurai,2025-04-15,Cash,2085
14,1015,221,South Delight,Pasta,5,417,45,Trichy,2025-02-01,Card,2085
3,1004,271,South Delight,Fried Rice,5,406,30,Madurai,2025-04-03,UPI,2030
17,1018,287,Urban Tadka,Biryani,5,394,39,Chennai,2025-03-08,Cash,1970

In [10]:
df[df["City"] == "Chennai"]

,Order_ID,Customer_ID,Restaurant,Food_Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price
2,1003,214,Spice Hub,Pizza,1,324,41,Chennai,2025-01-24,UPI,324
6,1007,282,Pizza Palace,Pizza,1,251,28,Chennai,2025-02-22,UPI,251
8,1009,274,Pizza Palace,Sandwich,2,473,35,Chennai,2025-04-09,UPI,946
15,1016,252,Food Fiesta,Sandwich,4,151,22,Chennai,2025-03-28,Card,604
17,1018,287,Urban Tadka,Biryani,5,394,39,Chennai,2025-03-08,Cash,1970
19,1020,237,South Delight,Pasta,5,486,26,Chennai,2025-01-25,Cash,2430
23,1024,220,Urban Tadka,Biryani,3,180,37,Chennai,2025-02-27,Card,540
24,1025,232,Urban Tadka,Fried Rice,4,286,59,Chennai,2025-03-08,UPI,1144
34,1035,259,Pizza Palace,Burger,4,225,35,Chennai,2025-01-27,Cash,900
36,1037,214,South Delight,Pasta,2,152,21,Chennai,2025-01-02,UPI,304
43,1044,263,Food Fiesta,Dosa,1,302,54,Chennai,2025-04-28,Cash,302
44,1045,202,Pizza Palace,Pasta,4,283,38,Chennai,2025-02-17,Cash,1132

In [11]:
df["Payment_Method"].value_counts()

Payment_Method
Card    21
Cash    15
UPI     14
Name: count, dtype: int64

In [12]:
df.groupby("Restaurant")["Total_Price"].sum()

Restaurant
Burger Town       1835
Food Fiesta       5086
Pizza Palace     14138
South Delight    15025
Spice Hub         4083
Urban Tadka       7497
Name: Total_Price, dtype: int64

In [13]:
df["Order_Category"] = df["Total_Price"].apply(
    lambda x: "High" if x > 500 else "Medium" if x > 200 else "Low")
df.head()

,Order_ID,Customer_ID,Restaurant,Food_Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category
0,1001,251,Pizza Palace,Dosa,5,417,53,Madurai,2025-04-15,Cash,2085,High
1,1002,292,South Delight,Fried Rice,3,264,25,Coimbatore,2025-02-06,Card,792,High
2,1003,214,Spice Hub,Pizza,1,324,41,Chennai,2025-01-24,UPI,324,Medium
3,1004,271,South Delight,Fried Rice,5,406,30,Madurai,2025-04-03,UPI,2030,High
4,1005,260,Urban Tadka,Sandwich,2,333,35,Madurai,2025-04-23,Card,666,High

In [14]:
df.rename(columns={"Food_Item":"Item"}, inplace=True)
df.head()

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category
0,1001,251,Pizza Palace,Dosa,5,417,53,Madurai,2025-04-15,Cash,2085,High
1,1002,292,South Delight,Fried Rice,3,264,25,Coimbatore,2025-02-06,Card,792,High
2,1003,214,Spice Hub,Pizza,1,324,41,Chennai,2025-01-24,UPI,324,Medium
3,1004,271,South Delight,Fried Rice,5,406,30,Madurai,2025-04-03,UPI,2030,High
4,1005,260,Urban Tadka,Sandwich,2,333,35,Madurai,2025-04-23,Card,666,High

In [15]:
df["City"] = df["City"].str.upper()
df.head()

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category
0,1001,251,Pizza Palace,Dosa,5,417,53,MADURAI,2025-04-15,Cash,2085,High
1,1002,292,South Delight,Fried Rice,3,264,25,COIMBATORE,2025-02-06,Card,792,High
2,1003,214,Spice Hub,Pizza,1,324,41,CHENNAI,2025-01-24,UPI,324,Medium
3,1004,271,South Delight,Fried Rice,5,406,30,MADURAI,2025-04-03,UPI,2030,High
4,1005,260,Urban Tadka,Sandwich,2,333,35,MADURAI,2025-04-23,Card,666,High

In [17]:
df[["Quantity","Price","Delivery_Time"]].corr()

               Quantity     Price  Delivery_Time
Quantity       1.000000 -0.002684       0.052086
Price         -0.002684  1.000000       0.078791
Delivery_Time  0.052086  0.078791       1.000000

In [22]:
df["Restaurant"]=df["Restaurant"].str.lower()
df.head()

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category
0,1001,251,pizza palace,Dosa,5,417,53,MADURAI,2025-04-15,Cash,2085,High
1,1002,292,south delight,Fried Rice,3,264,25,COIMBATORE,2025-02-06,Card,792,High
2,1003,214,spice hub,Pizza,1,324,41,CHENNAI,2025-01-24,UPI,324,Medium
3,1004,271,south delight,Fried Rice,5,406,30,MADURAI,2025-04-03,UPI,2030,High
4,1005,260,urban tadka,Sandwich,2,333,35,MADURAI,2025-04-23,Card,666,High

In [23]:
quantity_array = np.array(df["Quantity"])

print(quantity_array)

[5 3 1 5 2 3 1 2 2 4 5 3 1 4 5 4 5 5 3 5 4 5 3 3 4 2 2 5 1 5 4 4 4 4 4 3 2
 4 1 1 1 1 3 1 4 5 1 3 3 1]

In [24]:
print("Average Quantity:", np.mean(quantity_array))
print("Max Quantity:", np.max(quantity_array))
print("Min Quantity:", np.min(quantity_array))

Average Quantity: 3.12
Max Quantity: 5
Min Quantity: 1

In [25]:
new_quantity = quantity_array + 2

print(new_quantity[:10])

[7 5 3 7 4 5 3 4 4 6]

In [26]:
matrix = np.array([[1,2],[3,4]])
print("Determinant:", np.linalg.det(matrix))
print("Inverse:", np.linalg.inv(matrix))
print("Eigenvalues:", np.linalg.eig(matrix)[0])

Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]

In [27]:
df.groupby("Item")["Quantity"].sum().sort_values(ascending=False).head()

Item
Biryani     30
Pasta       30
Pizza       28
Sandwich    19
Dosa        16
Name: Quantity, dtype: int64

In [28]:
df["City"].value_counts()

City
COIMBATORE    13
MADURAI       12
CHENNAI       12
TRICHY         9
SALEM          4
Name: count, dtype: int64

In [29]:
df["Delivery_Time"].mean()

np.float64(39.36)

In [30]:
top_order = df.sort_values(by="Total_Price", ascending=False).head(1)

print(top_order)

    Order_ID  Customer_ID     Restaurant   Item  Quantity  Price  \
19      1020          237  south delight  Pasta         5    486

    Delivery_Time     City Order_Date Payment_Method  Total_Price  \
19             26  CHENNAI 2025-01-25           Cash         2430

   Order_Category
19           High

In [45]:
df[df["Price"] > 100]

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category,Day,Weekday,Month
0,1001,251,pizza palace,Dosa,5,417,53,MADURAI,2025-04-15,Cash,2085,High,15,Tuesday,4
1,1002,292,south delight,Fried Rice,3,264,25,COIMBATORE,2025-02-06,Card,792,High,6,Thursday,2
2,1003,214,spice hub,Pizza,1,324,41,CHENNAI,2025-01-24,UPI,324,Medium,24,Friday,1
3,1004,271,south delight,Fried Rice,5,406,30,MADURAI,2025-04-03,UPI,2030,High,3,Thursday,4
4,1005,260,urban tadka,Sandwich,2,333,35,MADURAI,2025-04-23,Card,666,High,23,Wednesday,4
5,1006,220,pizza palace,Fried Rice,3,271,52,COIMBATORE,2025-02-15,Cash,813,High,15,Saturday,2
6,1007,282,pizza palace,Pizza,1,251,28,CHENNAI,2025-02-22,UPI,251,Medium,22,Saturday,2
7,1008,286,spice hub,Pizza,2,414,25,COIMBATORE,2025-04-05,UPI,828,High,5,Saturday,4
8,1009,274,pizza palace,Sandwich,2,473,35,CHENNAI,2025-04-09,UPI,946,High,9,Wednesday,4
9,1010,274,food fiesta,Pizza,4,259,48,TRICHY,2025-03-01,Card,1036,High,1,Saturday,3
10,1011,287,pizza palace,Pasta,5,195,22,SALEM,2025-04-07,Card,975,High,7,Monday,4
11,1012,299,south delight,Pizza,3,332,39,SALEM,2025-04-26,Cash,996,High,26,Saturday,4
12,1013,223,south delight,Dosa,1,279,55,SALEM,2025-03-04,Cash,279,Medium,4,Tuesday,3
13,1014,202,south delight,Pasta,4,212,38,COIMBATORE,2025-03-26,Cash,848,High,26,Wednesday,3
14,1015,221,south delight,Pasta,5,417,45,TRICHY,2025-02-01,Card,2085,High,1,Saturday,2
15,1016,252,food fiesta,Sandwich,4,151,22,CHENNAI,2025-03-28,Card,604,High,28,Friday,3
16,1017,201,burger town,Biryani,5,367,38,MADURAI,2025-02-02,Cash,1835,High,2,Sunday,2
17,1018,287,urban tadka,Biryani,5,394,39,CHENNAI,2025-03-08,Cash,1970,High,8,Saturday,3
18,1019,229,spice hub,Pizza,3,485,51,MADURAI,2025-01-18,Card,1455,High,18,Saturday,1
19,1020,237,south delight,Pasta,5,486,26,CHENNAI,2025-01-25,Cash,2430,High,25,Saturday,1
20,1021,201,pizza palace,Biryani,4,212,52,TRICHY,2025-04-16,UPI,848,High,16,Wednesday,4
21,1022,263,south delight,Biryani,5,200,59,MADURAI,2025-04-05,Card,1000,High,5,Saturday,4
22,1023,259,pizza palace,Pizza,3,212,58,COIMBATORE,2025-02-23,Cash,636,High,23,Sunday,2
23,1024,220,urban tadka,Biryani,3,180,37,CHENNAI,2025-02-27,Card,540,High,27,Thursday,2
24,1025,232,urban tadka,Fried Rice,4,286,59,CHENNAI,2025-03-08,UPI,1144,High,8,Saturday,3
25,1026,275,urban tadka,Burger,2,212,20,MADURAI,2025-04-14,Card,424,Medium,14,Monday,4
26,1027,257,pizza palace,Sandwich,2,101,30,COIMBATORE,2025-02-15,Card,202,Medium,15,Saturday,2
27,1028,221,south delight,Burger,5,229,47,COIMBATORE,2025-01-24,Card,1145,High,24,Friday,1
28,1029,288,urban tadka,Pizza,1,319,44,TRICHY,2025-04-24,Card,319,Medium,24,Thursday,4
29,1030,248,food fiesta,Dosa,5,153,42,COIMBATORE,2025-02-01,UPI,765,High,1,Saturday,2
30,1031,290,pizza palace,Sandwich,4,442,50,COIMBATORE,2025-02-16,Card,1768,High,16,Sunday,2
31,1032,258,pizza palace,Pizza,4,323,49,COIMBATORE,2025-03-27,Card,1292,High,27,Thursday,3
32,1033,241,south delight,Pasta,4,324,54,SALEM,2025-01-23,Cash,1296,High,23,Thursday,1
33,1034,291,pizza palace,Dosa,4,484,26,TRICHY,2025-03-07,Card,1936,High,7,Friday,3
34,1035,259,pizza palace,Burger,4,225,35,CHENNAI,2025-01-27,Cash,900,High,27,Monday,1
35,1036,279,urban tadka,Pizza,3,229,45,MADURAI,2025-04-16,UPI,687,High,16,Wednesday,4
36,1037,214,south delight,Pasta,2,152,21,CHENNAI,2025-01-02,UPI,304,Medium,2,Thursday,1
37,1038,261,urban tadka,Sandwich,4,271,20,TRICHY,2025-03-31,UPI,1084,High,31,Monday,3
38,1039,261,urban tadka,Sandwich,1,317,31,MADURAI,2025-01-17,UPI,317,Medium,17,Friday,1
39,1040,246,south delight,Noodles,1,259,24,TRICHY,2025-04-14,Cash,259,Medium,14,Monday,4
40,1041,261,spice hub,Pasta,1,297,56,COIMBATORE,2025-02-02,Card,297,Medium,2,Sunday,2
41,1042,250,urban tadka,Fried Rice,1,346,51,MADURAI,2025-01-09,UPI,346,Medium,9,Thursday,1
42,1043,254,food fiesta,Biryani,3,423,28,COIMBATORE,2025-02-12,Card,1269,High,12,Wednesday,2
43,1044,263,food fiesta,Dosa,1,302,54,CHENNAI,2025-04-28,Cash,302,Medium,28,Monday,4
44,1045,202,pizza palace,Pasta,4,283,38,CHENNAI,2025-02-17,Cash,1132,High,17,Monday,2
45,1046,250,food fiesta,Noodles,5,222,35,MADURAI,2025-02-08,Cash,1110,High,8,Saturday,2
46,1047,206,pizza palace,Biryani,1,354,22,MADURAI,2025-04-03,UPI,354,Medium,3,Thursday,4
47,1048,220,spice hub,Biryani,3,393,39,TRICHY,2025-02-11,Card,1179,High,11,Tuesday,2
48,1049,272,south delight,Pizza,3,379,43,TRICHY,2025-04-29,Card,1137,High,29,Tuesday,4
49,1050,238,south delight,Biryani,1,424,52,COIMBATORE,2025-01-26,Card,424,Medium,26,Sunday,1

In [46]:
df["Price"].sum()
df["Price"].mean()
df["Price"].max()
df["Price"].min()

101

In [54]:
df["Restaurant"].value_counts().head(5)

Restaurant
pizza palace     14
south delight    14
urban tadka      10
food fiesta       6
spice hub         5
Name: count, dtype: int64

In [55]:
df["Total_Price"].max()

2430

In [56]:
df.groupby("City")["Order_ID"].count()

City
CHENNAI       12
COIMBATORE    13
MADURAI       12
SALEM          4
TRICHY         9
Name: Order_ID, dtype: int64

In [57]:
df["Delivery_Time"].mean()

np.float64(39.36)

In [58]:
df["Payment_Method"].value_counts()

Payment_Method
Card    21
Cash    15
UPI     14
Name: count, dtype: int64

In [59]:
df[["Quantity","Price","Delivery_Time"]].corr()

               Quantity     Price  Delivery_Time
Quantity       1.000000 -0.002684       0.052086
Price         -0.002684  1.000000       0.078791
Delivery_Time  0.052086  0.078791       1.000000

In [60]:
df[df["Total_Price"] > 500]

,Order_ID,Customer_ID,Restaurant,Item,Quantity,Price,Delivery_Time,City,Order_Date,Payment_Method,Total_Price,Order_Category,Day,Weekday,Month
0,1001,251,pizza palace,Dosa,5,417,53,MADURAI,2025-04-15,Cash,2085,High,15,Tuesday,4
1,1002,292,south delight,Fried Rice,3,264,25,COIMBATORE,2025-02-06,Card,792,High,6,Thursday,2
3,1004,271,south delight,Fried Rice,5,406,30,MADURAI,2025-04-03,UPI,2030,High,3,Thursday,4
4,1005,260,urban tadka,Sandwich,2,333,35,MADURAI,2025-04-23,Card,666,High,23,Wednesday,4
5,1006,220,pizza palace,Fried Rice,3,271,52,COIMBATORE,2025-02-15,Cash,813,High,15,Saturday,2
7,1008,286,spice hub,Pizza,2,414,25,COIMBATORE,2025-04-05,UPI,828,High,5,Saturday,4
8,1009,274,pizza palace,Sandwich,2,473,35,CHENNAI,2025-04-09,UPI,946,High,9,Wednesday,4
9,1010,274,food fiesta,Pizza,4,259,48,TRICHY,2025-03-01,Card,1036,High,1,Saturday,3
10,1011,287,pizza palace,Pasta,5,195,22,SALEM,2025-04-07,Card,975,High,7,Monday,4
11,1012,299,south delight,Pizza,3,332,39,SALEM,2025-04-26,Cash,996,High,26,Saturday,4
13,1014,202,south delight,Pasta,4,212,38,COIMBATORE,2025-03-26,Cash,848,High,26,Wednesday,3
14,1015,221,south delight,Pasta,5,417,45,TRICHY,2025-02-01,Card,2085,High,1,Saturday,2
15,1016,252,food fiesta,Sandwich,4,151,22,CHENNAI,2025-03-28,Card,604,High,28,Friday,3
16,1017,201,burger town,Biryani,5,367,38,MADURAI,2025-02-02,Cash,1835,High,2,Sunday,2
17,1018,287,urban tadka,Biryani,5,394,39,CHENNAI,2025-03-08,Cash,1970,High,8,Saturday,3
18,1019,229,spice hub,Pizza,3,485,51,MADURAI,2025-01-18,Card,1455,High,18,Saturday,1
19,1020,237,south delight,Pasta,5,486,26,CHENNAI,2025-01-25,Cash,2430,High,25,Saturday,1
20,1021,201,pizza palace,Biryani,4,212,52,TRICHY,2025-04-16,UPI,848,High,16,Wednesday,4
21,1022,263,south delight,Biryani,5,200,59,MADURAI,2025-04-05,Card,1000,High,5,Saturday,4
22,1023,259,pizza palace,Pizza,3,212,58,COIMBATORE,2025-02-23,Cash,636,High,23,Sunday,2
23,1024,220,urban tadka,Biryani,3,180,37,CHENNAI,2025-02-27,Card,540,High,27,Thursday,2
24,1025,232,urban tadka,Fried Rice,4,286,59,CHENNAI,2025-03-08,UPI,1144,High,8,Saturday,3
27,1028,221,south delight,Burger,5,229,47,COIMBATORE,2025-01-24,Card,1145,High,24,Friday,1
29,1030,248,food fiesta,Dosa,5,153,42,COIMBATORE,2025-02-01,UPI,765,High,1,Saturday,2
30,1031,290,pizza palace,Sandwich,4,442,50,COIMBATORE,2025-02-16,Card,1768,High,16,Sunday,2
31,1032,258,pizza palace,Pizza,4,323,49,COIMBATORE,2025-03-27,Card,1292,High,27,Thursday,3
32,1033,241,south delight,Pasta,4,324,54,SALEM,2025-01-23,Cash,1296,High,23,Thursday,1
33,1034,291,pizza palace,Dosa,4,484,26,TRICHY,2025-03-07,Card,1936,High,7,Friday,3
34,1035,259,pizza palace,Burger,4,225,35,CHENNAI,2025-01-27,Cash,900,High,27,Monday,1
35,1036,279,urban tadka,Pizza,3,229,45,MADURAI,2025-04-16,UPI,687,High,16,Wednesday,4
37,1038,261,urban tadka,Sandwich,4,271,20,TRICHY,2025-03-31,UPI,1084,High,31,Monday,3
42,1043,254,food fiesta,Biryani,3,423,28,COIMBATORE,2025-02-12,Card,1269,High,12,Wednesday,2
44,1045,202,pizza palace,Pasta,4,283,38,CHENNAI,2025-02-17,Cash,1132,High,17,Monday,2
45,1046,250,food fiesta,Noodles,5,222,35,MADURAI,2025-02-08,Cash,1110,High,8,Saturday,2
47,1048,220,spice hub,Biryani,3,393,39,TRICHY,2025-02-11,Card,1179,High,11,Tuesday,2
48,1049,272,south delight,Pizza,3,379,43,TRICHY,2025-04-29,Card,1137,High,29,Tuesday,4

In [61]:
city_orders = df.groupby("City")["Order_ID"].count().sort_values(ascending=False)

print(city_orders)

City
COIMBATORE    13
CHENNAI       12
MADURAI       12
TRICHY         9
SALEM          4
Name: Order_ID, dtype: int64

In [62]:
df["Total_Price"] = df["Quantity"] * df["Price"]
restaurant_revenue = df.groupby("Restaurant")["Total_Price"].sum().sort_values(ascending=False)
print(restaurant_revenue)

Restaurant
south delight    15025
pizza palace     14138
urban tadka       7497
food fiesta       5086
spice hub         4083
burger town       1835
Name: Total_Price, dtype: int64

In [63]:
payment_analysis = df["Payment_Method"].value_counts()

print(payment_analysis)

Payment_Method
Card    21
Cash    15
UPI     14
Name: count, dtype: int64

In [64]:
daily_orders = df.groupby("Order_Date")["Order_ID"].count()

print(daily_orders)

Order_Date
2025-01-02    1
2025-01-09    1
2025-01-17    1
2025-01-18    1
2025-01-23    1
2025-01-24    2
2025-01-25    1
2025-01-26    1
2025-01-27    1
2025-02-01    2
2025-02-02    2
2025-02-06    1
2025-02-08    1
2025-02-11    1
2025-02-12    1
2025-02-15    2
2025-02-16    1
2025-02-17    1
2025-02-22    1
2025-02-23    1
2025-02-27    1
2025-03-01    1
2025-03-04    1
2025-03-07    1
2025-03-08    2
2025-03-26    1
2025-03-27    1
2025-03-28    1
2025-03-31    1
2025-04-03    2
2025-04-05    2
2025-04-07    1
2025-04-09    1
2025-04-14    2
2025-04-15    1
2025-04-16    2
2025-04-23    1
2025-04-24    1
2025-04-26    1
2025-04-28    1
2025-04-29    1
Name: Order_ID, dtype: int64

In [66]:
df[["Quantity","Order_ID","Customer_ID"]].corr()

             Quantity  Order_ID  Customer_ID
Quantity     1.000000 -0.207257     -0.04852
Order_ID    -0.207257  1.000000     -0.13705
Customer_ID -0.048520 -0.137050      1.00000

In [71]:
df[["Order_Date","Price","Delivery_Time"]].corr()

               Order_Date     Price  Delivery_Time
Order_Date       1.000000 -0.029702      -0.090005
Price           -0.029702  1.000000       0.078791
Delivery_Time   -0.090005  0.078791       1.000000